name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
      - name: Run unit tests
        run: python -m coverage run -m unittest schubertpy/testcases/basic/*.py
      - name: Generate coverage report
        run: |
          python -m coverage xml
          python -m coverage html
          python -m coverage report -m
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov
      - name: Coverage comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Generate extra coverage badges
        run: |
          pip install diff-cover
          python scripts/coverage_badges.py
      - name: Commit extra badges
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git checkout python-coverage-comment-action-data
          mv ../evolution_endpoint.json . || true
          mv ../pr_endpoint.json . || true
          git add evolution_endpoint.json pr_endpoint.json
          git commit -m "Update extra coverage badges" || echo "No changes"
          git push origin HEAD:python-coverage-comment-action-data
